
# ignore all warnings from all pods
inhibit_all_warnings!

platform :ios, "8.1"

target "LARGruop" do

pod 'HockeySDK', '3.8.5' 
pod 'AFNetworking'
pod 'Reachability', '3.1.1'
pod 'MRProgress'
pod 'MagicalRecord'
pod 'SCLAlertView-Objective-C'
pod 'JTCalendar', '~> 2.0'
pod 'CGLAlphabetizer', '~> 0.1'
pod 'EDStarRating'
pod 'Haneke', '~> 1.0'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDWebImage', '~>3.7'
end
